# Generated by Django 4.2.3 on 2024-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('Image', models.ImageField(height_field=30, max_length=50, upload_to='products/images', width_field=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
