# Generated by Django 4.2.3 on 2024-07-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
